"""empty message

Revision ID: 198b6dbccde2
Revises: 86269d851f1f
Create Date: 2022-09-22 20:21:19.454607

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "198b6dbccde2"
down_revision = "86269d851f1f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bet",
        "state",
        existing_type=sa.VARCHAR(length=16),
        type_=sa.String(length=10),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bet",
        "state",
        existing_type=sa.String(length=10),
        type_=sa.VARCHAR(length=16),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
