"""empty message

Revision ID: 5bcf87ac5111
Revises: fc41aa7b4478
Create Date: 2022-09-22 23:07:17.540321

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5bcf87ac5111"
down_revision = "fc41aa7b4478"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bet",
        sa.Column("bet_amount", sa.Numeric(precision=14, scale=4), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bet", "bet_amount")
    # ### end Alembic commands ###
