"""empty message

Revision ID: fc41aa7b4478
Revises: 198b6dbccde2
Create Date: 2022-09-22 20:27:24.658643

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fc41aa7b4478"
down_revision = "198b6dbccde2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bet", sa.Column("event_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bet", "event_id")
    # ### end Alembic commands ###
