# Docker compose file for local development

version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    depends_on: [ database, backend-migration ]
    env_file: .env
    healthcheck:
      test: "curl --fail http://localhost:8000/healthcheck || exit 1"
      interval: 5s
      timeout: 10s
      retries: 3

  database:
    image: postgres:14
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 5
    env_file:
      - .database.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend-migrate:
    build: .
    depends_on:
      database:
        condition: service_healthy
    entrypoint: ["alembic", "upgrade", "head"]
    env_file: .env

volumes:
  postgres-data:
